# Generated by Django 5.1.4 on 2026-05-31 19:48

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('awaiting_review', 'Awaiting review'), ('graded', 'Graded')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=12)),
                ('prompt', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('difficulty', models.CharField(blank=True, max_length=4)),
                ('accepted_text', models.CharField(blank=True, max_length=255)),
                ('numeric_answer', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('image_requirement', models.TextField(blank=True)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='quiz.attempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('attempt', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('selected_choice_ids', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to=quiz.models.attempt_image_path)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_answers', to=settings.AUTH_USER_MODEL)),
                ('attempt_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.attemptquestion')),
            ],
        ),
    ]
