# Generated by Django 5.1.4 on 2026-05-31 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text (free response)'), ('single', 'Single choice'), ('multiple', 'Multiple choice'), ('numerical', 'Numerical input'), ('image', 'Image upload')], max_length=12)),
                ('prompt', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('med', 'Medium'), ('hard', 'Hard')], default='med', max_length=4)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive questions are excluded from the quiz pool.')),
                ('accepted_text', models.CharField(blank=True, help_text='Accepted answer for text questions.', max_length=255)),
                ('numeric_answer', models.DecimalField(blank=True, decimal_places=6, help_text='Correct value for numerical questions.', max_digits=20, null=True)),
                ('image_requirement', models.TextField(blank=True, help_text='What the uploaded image must show (for reviewers).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
